sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t rcampos1973/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true rcampos1973/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-182130275609"
  bucket_path: "docker"
on:
  branch: master
access_key_id: $AWS_ACCESS_KEY_DOCKER_REACT
secret_access_key:
  secure: $AWS_SECRET_KEY_DOCKER_REACT
